//! Exhaustive checks on `nucleus_state`, the per-keystroke nucleus validator.
//!
//! [`nucleus_state`] dispatches through a flat table generated by the
//! `state_match!` macro, bucketed by arity. Two properties are easy to break
//! and impossible to see from a handful of hand-picked examples:
//!
//! 1. **The 4+ vowel case.** `NUCLEUS_MAX_LEN` is 3, so anything longer falls
//!    into the macro's `_ => Dead` arm. A silent `Dead` for a 4-vowel nucleus
//!    would reject real input; a silent `Valid` would accept nonsense.
//! 2. **The population counts.** The table encodes exactly which nuclei are
//!    real Vietnamese. Refactoring the table (say, into a packed dispatch)
//!    can change the answers for sequences nobody thought to try. Pinning the
//!    Valid / InComplete / Dead distribution over *every* 1..=3 combination
//!    catches that as a count change.
//!
//! The counts themselves used to be asserted inside `bench_nucleus_state`,
//! which meant they only ran on `cargo bench` and were lost the moment that
//! A/B bench was deleted. This is the same assertion, as a test.

use vime_engine::phonology::{nucleus_state, BaseVowel, NucleusState, NUCLEUS_MAX_LEN};

/// Every base vowel, in declaration order. Adding a variant means adding a row
/// here, and the population counts below will move — which is the point.
const ALL_VOWELS: &[BaseVowel] = &[
    BaseVowel::Y,
    BaseVowel::U,
    BaseVowel::I,
    BaseVowel::E,
    BaseVowel::O,
    BaseVowel::A,
    BaseVowel::UHorn,
    BaseVowel::ACircumflex,
    BaseVowel::OCircumflex,
    BaseVowel::ABreve,
    BaseVowel::ECircumflex,
    BaseVowel::OHorn,
];

/// Every nucleus of length 1..=3: 12 + 144 + 1728 = 1884 sequences.
fn all_nuclei() -> Vec<Vec<BaseVowel>> {
    let mut out = Vec::new();
    for &a in ALL_VOWELS {
        out.push(vec![a]);
    }
    for &a in ALL_VOWELS {
        for &b in ALL_VOWELS {
            out.push(vec![a, b]);
        }
    }
    for &a in ALL_VOWELS {
        for &b in ALL_VOWELS {
            for &c in ALL_VOWELS {
                out.push(vec![a, b, c]);
            }
        }
    }
    out
}

/// The state distribution is pinned, so a table refactor that silently
/// reclassifies a family cannot pass unnoticed.
#[test]
fn nucleus_state_population_is_pinned() {
    let all = all_nuclei();

    let mut valid = 0;
    let mut incomplete = 0;
    let mut dead = 0;
    for nucleus in &all {
        match nucleus_state(nucleus.as_slice()) {
            NucleusState::Valid => valid += 1,
            NucleusState::InComplete => incomplete += 1,
            NucleusState::Dead => dead += 1,
        }
    }

    assert_eq!(
        (all.len(), valid, incomplete, dead),
        (1884, 56, 17, 1811),
        "nucleus table drifted: 12 + 12^2 + 12^3 = 1884 sequences, \
         of which 56 are real nuclei and 17 are real-but-unfinished"
    );
}

/// A single vowel is always a usable nucleus, and the empty one is always
/// merely incomplete — never `Dead`, or the builder would reject a word at its
/// first keystroke.
#[test]
fn every_single_vowel_is_valid() {
    for &vowel in ALL_VOWELS {
        assert_eq!(
            nucleus_state(&[vowel]),
            NucleusState::Valid,
            "{vowel:?} should be a complete nucleus on its own"
        );
    }
    assert_eq!(nucleus_state(&[] as &[BaseVowel]), NucleusState::InComplete);
}

/// `NUCLEUS_MAX_LEN` is 3, so a longer nucleus is not a nucleus at all.
///
/// This is the one bound the test suite did not previously pin: the benches
/// only ever generated sequences of length 1..=3, so the `_ => Dead` arm of
/// the table was never exercised.
#[test]
fn nuclei_longer_than_the_maximum_are_dead() {
    assert_eq!(NUCLEUS_MAX_LEN, 3, "this test assumes a max length of 3");

    for len in NUCLEUS_MAX_LEN + 1..=NUCLEUS_MAX_LEN + 3 {
        // Vary the tail so the test cannot pass on a repeated-suffix quirk.
        let mut nucleus = vec![BaseVowel::A; len];
        nucleus[3] = BaseVowel::I;
        assert_eq!(
            nucleus_state(nucleus.as_slice()),
            NucleusState::Dead,
            "a {len}-vowel nucleus is past NUCLEUS_MAX_LEN, so it must be dead: {nucleus:?}"
        );
    }
}
